import Head from "next/head";
import { FaSearch, FaMapMarkerAlt } from "react-icons/fa";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[calc(100vh_-_120px)] flex justify-center items-center">
        <div className="text-center -mt-32">
          <div className="text-[32px] md:text-[74px] text-center font-bold font-inter">
            <div>
              <span>Get The </span>
              <span className="text-primary-blue">Right Job</span>
            </div>
            <span>You Deserve</span>
          </div>
          <div className="my-5">
            800 jobs listed here, your dream job is waiting
          </div>
        <div className="mt-10 custom-shadow rounded-full py-4 px-4">
          <form className=" flex justify-between items-center">
            <div className="relative">
              <input type="text" className="pl-5 text-start w-1/2 sm:w-full" placeholder="Job title or keyword" />
              <div className="absolute left-0 top-1">
                <FaSearch />
              </div>
            </div>
            <div className="relative">
              <input type="text" className="pl-5 w-1/2 sm:w-full" placeholder="Kaduna" />
              <div className="absolute left-0 top-1">
                <FaMapMarkerAlt />
              </div>
            </div>
            <div>
              <button className="bg-primary-blue rounded-3xl px-5 py-2 text-white">Search</button>
            </div>
          </form>

        </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
