import Head from "next/head";
import { FaSearch, FaMapMarkerAlt } from "react-icons/fa";
import styles from "../styles/Home.module.css";
import { dummyFeatured } from "../data";
import FeaturedCard from '../components/Home/FeatureCard'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jobsmole - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner section */}
      <div className="h-[calc(100vh_-_120px)] flex justify-center items-center">
        <div className="text-center -mt-32">
          <div className="text-[32px] md:text-[74px] text-center font-bold font-inter">
            <div>
              <span>Get The </span>
              <span className="text-primary-blue">Right Job</span>
            </div>
            <span>You Deserve</span>
          </div>
          <div className="my-5">
            800 jobs listed here, your dream job is waiting
          </div>
          <div className="mt-10 custom-shadow rounded-full mx-2 py-4 px-4">
            <form className=" flex justify-between items-center mx-2">
              <div className="relative">
                <input
                  type="text"
                  className="sm:pl-5 text-start w-1/2 sm:w-full outline-none text-xs sm:text-base"
                  placeholder="Job title or keyword"
                />
                <div className="absolute left-0 top-1">
                  <FaSearch color="lightgrey" />
                </div>
              </div>
              <div className="relative">
                <input
                  type="text"
                  className="sm:pl-5 w-1/2 sm:w-full outline-none text-xs sm:text-base"
                  placeholder="Kaduna"
                />
                <div className="absolute left-0 top-1">
                  <FaMapMarkerAlt color="lightgrey" />
                </div>
              </div>
              <div>
                <button className="bg-primary-blue text-xs sm:text-base rounded-3xl px-5 py-2 text-white">
                  Search
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

      {/* featured jobs */}
      <div className="bg-primary-light p-4">
        <div className="max-w-[1440px] mx-auto flex items-center justify-center min-h-screen">
          <div className="">
            <div className="text-center text-[32px] mb-10 md:text-[44px] font-bold font-inter">
              <h2>One Platform</h2>
              <div>
                <span>Many </span>
                <span className="text-primary-blue">Solutions</span>
              </div>
            </div>
            <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {dummyFeatured.map((item, idx) => (
                <FeaturedCard item={item} key={idx} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
